[package]
name = "sabun_data_model"
version = "0.1.0"
authors = ["reddi <reddit_chan@outlook.jp>"]
edition = "2018"

[dependencies]
sabun_maker = { path = "./sabun_maker"}
json5_parser = { path = "./json5" }