[package]
name = "general_compaction"
version = "0.1.0"
authors = ["reddi <reddit_chan@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.1"
regex = "1"
lazy_static="1.4"